### ISSUE TITLE
Work with numbers too

### ISSUE THREAD

**Issue by molinto** [wooorm/retext-syllable#1]
More of a idea really, it would be great to get the syllable count when numbers are within a sentence too, eg: 50 great ways to get more facebook fans = 9, should be 10.

**Comment by wooorm** [comment]
Oh great idea, however, is that something this module should do, or would it be preferable to transform digits into human-spoken form, e.g., “fifty”, and then running that through retext-syllable?

**Comment by molinto** [comment]
Within this module I think, as text "fifty" already converts to 2 syllables.  

Numerical value "50" converted to textual representation "fifty", then syllable count.  Perhaps something like this: https://www.npmjs.com/package/number-to-words or https://github.com/nisaacson/number-string-representation

**Comment by wooorm** [comment]
Hmm, i might want to implement this in [wooorm/syllable](https://github.com/wooorm/syllable). My major issues here are that:
1.   What about comma’s and full-stops? Some languages use `10,00`, some use `10.00`. What about `10,000` and `10.000`? `10,0` and `10.0`?
2.   Second, **wooorm/syllable** doesn’t know about words, so there’s still some guessing here.
3.   Third, [number-string-representation](https://github.com/nisaacson/number-string-representation) seems to support decimals, but return digits in the resulting words (see the example [here](https://github.com/nisaacson/number-string-representation#negative-numbers)). P.S. [number-to-words](https://www.npmjs.com/package/number-to-words) doesn’t state if it supports them.

How to handle these issues?

**Comment by molinto** [comment]
Good point at the locale issue.  Don't worry about it dude.
